on:
  push:
    paths-ignore:
      - 'README.md'

jobs:
  setup:
    name: Choose Secrets Environment Job
    runs-on: windows-latest
    steps:
      - id: setup
        name: Setup Environment
        run: |
          Write-Host "Using github.ref for choosing build_env"      
          if ('${{ github.ref }}' -eq 'refs/heads/main') {
            Write-Host "Using prod for build_env"
            echo "::set-output name=build_env::prod"
          } else {
            Write-Host "Using dev for build_env"
            echo "::set-output name=build_env::dev"
          }
    outputs:
      build_env: ${{ steps.setup.outputs.build_env }}

  cd_deploy:
    name: Deploy Azure Environment
    needs:
      - setup
    environment: ${{ needs.setup.outputs.build_env }}
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2

      - name: Azure CLI Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          enable-AzPSSession: true

      - name: Build azure environment
        id: deploy
        uses: azure/arm-deploy@v1
        with:
          deploymentName: 'deploy-${{ needs.setup.outputs.build_env }}-${{ github.run_number }}'
          resourceGroupName: test-shared-services-dev
          template: ./deployment/deploy.bicep
          parameters: >
              solutionName=${{ secrets.SOLUTION_NAME }}